### ISSUE TITLE
Flesh out Fundamentals 1 - Git

### ISSUE THREAD

**Issue by luke-m** [virtualidentityag/dev-fe-onboarding#21]
IMO the explanation of the git workflow is not detailed enough. Stuff like `git commit`, `git push` should be mentioned for sure.

**Comment by jurekbarth** [comment]
@claudivieira would you be interested to fix it?

**Comment by claudivieira** [comment]
@jurekbarth sure!! :) 👍

**Comment by jurekbarth** [comment]
@claudivieira any status update here?

**Comment by jurekbarth** [comment]
@claudivieira any updates?

**Comment by claudivieira** [comment]
Checking with @bennyvi his schedule and starting in this issue ASAP.
