### ISSUE TITLE
Add transition to animation chapter

### ISSUE THREAD

**Issue by IvailoStoyanov** [virtualidentityag/dev-fe-onboarding#29]
https://developer.mozilla.org/en-US/docs/Web/CSS/transition

**Comment by jurekbarth** [comment]
@IvailoStoyanov could you please further explain your needs/thoughts?

**Comment by luke-m** [comment]
@jurekbarth This is just a headsup that transitions are missing from the fundamentals 2 chapter (I wrote the comment from his PC lol)

**Comment by luke-m** [comment]
We're gonna take care of all the issues once we have the next onboarding meeting
