### ISSUE TITLE
estimated time for each chapter

### ISSUE THREAD

**Issue by ItsmeEddi** [virtualidentityag/dev-fe-onboarding#41]
It would be nice to have something like an astimated time for each chapter, to get a feeling if you're behind, just in time or might be breezing through the chapters.

**Comment by jurekbarth** [comment]
@ItsmeEddi we didn't put a timeframe on purpose as far as i can remember. The reason for that was that nobody should feel pressured by any timeframe. On top everybody comes with a different knowledge level and thus it will take longer or shorter.
I think it's best to discuss timeframes with your technical onboader, what do you think?

**Comment by ItsmeEddi** [comment]
@jurekbarth Ok that makes sense, thank you!
