### ISSUE TITLE
All screens download link doesn't work

### ISSUE THREAD

**Issue by karlbaumhauer** [virtualidentityag/dev-fe-onboarding#46]
https://dev-fe-onboarding.virtual-identity.com/#/assets/fundamentals-1/biotope-onboaring-fundamentals-1-screens.zip just keeps loading. 

Had to go directly to the GitHub Repo to get the data which was as well a good experience to find data stored there. Might be a good exercise but in this case should be explained.

**Comment by jurekbarth** [comment]
Hi @karlbaumhauer,

the following link should work: https://dev-fe-onboarding.virtual-identity.com/assets/fundamentals-1/biotope-onboaring-fundamentals-1-screens.zip

Would you like to figure it out and submit your first pull request? Feel free to contact me if you need further help 👍

**Comment by dweiger** [comment]
Closed by #48
