### ISSUE TITLE
Roadmap & Goals could be better formated

### ISSUE THREAD

**Issue by dannystey** [virtualidentityag/dev-fe-onboarding#51]
**format**
Beside that I would also suggest to overthink the Roadmap. Some parts are confusing and the table element does not fit for the structure. Maybe it should be a list ore a own component, like a timeline. I would expect this following points in a roadmap:

- topic
- goals
- ?estimation (to have an orientation over the 3 months that are already estimated in here https://dev-fe-onboarding.virtual-identity.com/#/getting-started?id=roadmap)

**Comment by dweiger** [comment]
@dannystey I think we now have a duplication of the roadmap in the getting started. Shhould we remove it from The getting started section?
