### ISSUE TITLE
Restructure the Onboarding Points and Wordings

### ISSUE THREAD

**Issue by tobiaskatzinger** [virtualidentityag/dev-fe-onboarding#55]
I think it's better if every Chapter has the same Structure with the same Points and Wordings for example **Preparation** or **Prerequisites**. , or the Challenges have sometimes 1. 2. and so one and sometime only Points. 

I think it's much better if we have a Standart Structure. For example

- Intro 
- preparation 
- resources
- Challenges (with 1., 2., 3.) 
- Questions

**Comment by dweiger** [comment]
Lets discuss in #58.
