### ISSUE TITLE
Bring every challenge into the same structure

### ISSUE THREAD

**Issue by dannystey** [virtualidentityag/dev-fe-onboarding#58]
Its more __productive__ (you can just scan the topic first and can read the task whenever you have to dive in) and __measurable__ (whenever DoD, goals and durations are defined) for the newbie and 

Suggestion:
- title
  - no emotional title
- requirements
  - could explain the requirements of skills and thing that the devs have to prepare
- goal
  - 1 - 2 sentences. Which explains why the challenge is useful for the overall goal or for VI
- ?duration
  - in TW
- description
  - description of the challenge with context
- definition of done
  - what has to be done to pass the challenge
  - questions
- ressources
  - link set of guidelines or informations that could be useful for the challenge

**Comment by dweiger** [comment]
I like especially the part with the DOD you already refered in #57. I would not add a duration. Evry onboardie is diffrent and has a diffrent level of experience. I think it would lead to preassure. I would avoid that in the onboarding process.

**Comment by dweiger** [comment]
Closing this issue by #99. We have the DOD idea in #57 as a single improvement.
