### ISSUE TITLE
Basic Components /  Biotope playground -- add link

### ISSUE THREAD

**Issue by tobiaskatzinger** [virtualidentityag/dev-fe-onboarding#71]
In this area:

> Fork the biotope playground on Github and start exploring. Your mentor will help you get going. Try to figure out how Biotope works. Have a look at our documentation

It think it makes sence to add a link to the **documentation** and also to **github**

**Comment by simonbraunbrown** [comment]
just also wanted to open an issue on that :-)

**Comment by dweiger** [comment]
Closed by  #78
